# Generated by Django 6.0.4 on 2026-04-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
